Repository Kelompok-3-Capstone-Alterra-2023/Mobile, pull requests merged in 2023-05, with the labels that each got.

#11 007 consultation
  prevent/lib/view/screens/consultation/consultation_screen.dart
  prevent/lib/view/screens/login/login_screen.dart
Labels: bug, enhancement

#15 - add screen home screen
  prevent/lib/main.dart
  prevent/lib/view/screens/consultation_history/consultation_history_screen.dart
  prevent/lib/view/screens/home/home_screen.dart
  prevent/lib/view/screens/notification/notification_screen.dart
  prevent/lib/view/screens/profile/profile_screen.dart
  prevent/lib/view/widgets/home/bottom_nav.dart
  prevent/lib/view/widgets/home/menu_home.dart
  prevent/lib/view/widgets/home/side_bar.dart
  prevent/lib/view_models/home_view_model.dart
Labels: bug, documentation, enhancement

#16 0013 doctor details screen (slicing)
  prevent/assets/images/doctor_wide.png
  prevent/assets/images/garuda_pancasila.png
  prevent/lib/view/screens/detail_doctor/detail_doctor_screen.dart
  prevent/lib/view/widgets/foz_button.dart
Labels: documentation, enhancement

#17 0019 consultation history screen
  prevent/lib/view/screens/consultation_history/consultation_history_screen.dart
Labels: enhancement

#19 Adding Doctor Favorite Screen
  prevent/lib/view/screens/doctor_favorite/doctor_favorite_screem.dart
Labels: enhancement

#20 add screen: feature search article
  prevent/lib/main.dart
  prevent/lib/view/screens/article/search_article_screen.dart
  prevent/lib/view/screens/article/view_all_article_screen.dart
  prevent/lib/view_models/search_article_view_model.dart
Labels: enhancement

#24 0025 settings screen
  prevent/assets/images/warning_delete_account_image.png
  prevent/lib/main.dart
  prevent/lib/view/screens/home/home_screen.dart
  prevent/lib/view/screens/notification/notification_screen.dart
  prevent/lib/view/screens/settings/delete_account.dart
  prevent/lib/view/screens/settings/dropdown/drop_down.dart
  prevent/lib/view/screens/settings/dropdown/expanded_section.dart
  prevent/lib/view/screens/settings/dropdown/my_scrollbar.dart
  prevent/lib/view/screens/settings/language_select_settings.dart
  prevent/lib/view/screens/settings/notificationSettings.dart
  prevent/lib/view/screens/settings/settings_screen.dart
  prevent/lib/view/screens/settings/user_account_settings_screen.dart
  prevent/lib/view/screens/settings/warning_delete_account_screen.dart
  prevent/lib/view/widgets/home/side_bar.dart
  prevent/lib/view_models/settings_view_model.dart
  prevent/pubspec.lock
  prevent/pubspec.yaml
Labels: enhancement

#22 0022 profile screen (slicing)
  prevent/assets/images/dummy_profile.png
  prevent/lib/view/screens/profile/profile_screen.dart
  prevent/lib/view/widgets/home/bottom_nav.dart
Labels: enhancement
